# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build cradio'
on: push
jobs:
  job_1:
    name: build cradio left firmware
    steps:
      uses: ./.github/workflows/main.yml
      secrets: inherit
      with:
        board: '["nice_nano_v2"]'
        shield: '["cradio_left"]'
        custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
        kconfig: '["CONFIG_ZMK_MOUSE=y"]'
        branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
      # uses: actions/checkout@v3
      # uses: actions/upload-artifact@v3
      #   with:
      #     name: cradio-left
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
        with:
          name: cradio-left
  job_2:
    name: build cradio right firmware
    needs: job_1
    steps:
      uses: ./.github/workflows/main.yml
      secrets: inherit
      with:
        board: '["nice_nano_v2"]'
        shield: '["cradio_right"]'
        custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
        kconfig: '["CONFIG_ZMK_MOUSE=y"]'
        branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
      uses: actions/checkout@v3
      uses: actions/upload-artifact@v3
        with:
          name: cradio-right
  job_3:
      name: download cradio firmware
      runs-on: ubuntu-latest
      needs: job_2
      # steps:
      # - name: download artifact
      # uses: actions/download-artifact@v3

      steps:
        uses: actions/checkout@v3
       uses: actions/download-artifact@v3
      #   with:
      #     name: cradio-left
      #     path: ~/Downloads/
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: cradio-right    
      #     path: ~/Downloads/
              
      # # - name: Display structure of downloaded files
      # #   run: ls -R
